config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('survey/', include('survey.urls')),
    path('suggestions/', include('suggestions.urls')),
    path('rosetta/', include('rosetta.urls')),
]

suggestions/urls.py
from django.urls import path

from . import views

app_name = 'suggestions'

urlpatterns = [
    path('', views.suggestions_from_customer, name='suggestions'),
]

survey/urls.py
from django.urls import path

from . import views

app_name = 'survey'


urlpatterns = [
    path('', views.survey_page_view, name='survey'),
    path('food/', views.survey_list_view, name='survey_food'),
    path('about/', views.survey_abuout_us_view, name='about'),
    path('clean/', views.survey_clean_view, name='clean'),
]

suggestions/models.py
from django.db import models
from django.utils.translation import gettext as _ 



class CommentsSuggestions(models.Model):
    text = models.TextField(_("text"))
    date_time_created = models.DateTimeField(_("date time created"), auto_now_add=True)

   
    class Meta:
        verbose_name =_("comments and suggestions ")
        verbose_name_plural = _("comments and suggestions ")

    

survey/models.py
from django.db import models
from django.utils.translation import gettext as _ 


class Food(models.Model):
    title = models.CharField(_("title"), max_length=255)
    is_active = models.BooleanField(_("active"), default=True)
    date_time_created = models.DateField(_("date created"),  auto_now_add=True)

    class Meta:
        verbose_name =_("food")
        verbose_name_plural = _("food")

    def __str__(self):
        return self.title


class FoodQuality(models.Model):
    CHOICES = (
        ('4', _('perfect')),
        ('3', _('good')),
        ('2', _('manual')),
        ('1', _('bad')),
    )
    food = models.ForeignKey(Food, verbose_name=_("food"), on_delete=models.CASCADE)
    choice_quality = models.CharField(_('quality'), choices =CHOICES, max_length = 50)
    is_active = models.BooleanField(_("active"), default=True)

    class Meta:
        verbose_name =_("food quality")
        verbose_name_plural = _("food quality")


    def __str__(self):
        return self.food.title
    


class OurStrengths(models.Model):
    title = models.CharField(_("strength"), max_length=255)
    is_active = models.BooleanField(_("active"), default=True)
    date_time_created = models.DateTimeField(_("date time created"),  auto_now_add=True)

    class Meta:
        verbose_name =_("Strength")
        verbose_name_plural = _("Strength")


    def __str__(self):
        return self.title



class SurveyAboutUs(models.Model):
    strength = models.ForeignKey(OurStrengths, verbose_name=_("strength"), on_delete=models.CASCADE)
    yes_or_no = models.BooleanField(_("yes or no"), default=False)
    date_time_created = models.DateTimeField(_("date time created"),  auto_now_add=True)

    class Meta:
        verbose_name =_("survey about us")
        verbose_name_plural = _("survey about us")

    

#  Collection cleaning moldels

class CollectionCleaning(models.Model):
    title = models.CharField(_("title"), max_length=255)
    is_active = models.BooleanField(_("active"), default=True)
    date_time_created = models.DateField(_("date created"),  auto_now_add=True)

    class Meta:
        verbose_name =_("collection")
        verbose_name_plural = _("collection")

    def __str__(self):
        return self.title


class Cleaning(models.Model):
    CHOICES = (
        ('4', _('perfect')),
        ('3', _('good')),
        ('2', _('manual')),
        ('1', _('bad')),
    )
    cleaning_the_area = models.ForeignKey(CollectionCleaning, verbose_name=_("cleannig area"), on_delete=models.CASCADE)
    costomer_score = models.CharField(_("customer score"),choices=CHOICES, max_length=50)
    date_time_created = models.DateField(_("date created"),  auto_now_add=True)

    class Meta:
        verbose_name =_("coustomer score for cleaning ")
        verbose_name_plural = _("coustomer score for cleaning ")


    def __str__(self):
        return self.costomer_score

suggestions/forms.py
from django import forms

from .models import CommentsSuggestions

class CommentSuggestionsForm(forms.ModelForm):
    class Meta:
        model = CommentsSuggestions
        fields = ['text']

survey/forms.py
from django import forms

from .models import FoodQuality, Cleaning, SurveyAboutUs

class FoodForm(forms.ModelForm):
    class Meta:
        model = FoodQuality
        fields = ['food','choice_quality']


class SurveyAboutUsForm(forms.ModelForm):
    class Meta:
        model = SurveyAboutUs
        fields = ['strength','yes_or_no']



class CleanForm(forms.ModelForm):
    class Meta:
        model = Cleaning
        fields = ['cleaning_the_area','costomer_score']

suggestions/views.py
from django.shortcuts import render

from .forms import CommentSuggestionsForm

def suggestions_from_customer(request):
    if request.method =='POST':
        form = CommentSuggestionsForm(request.POST)
        if form.is_valid():
            form.save()
            form = CommentSuggestionsForm()
    else:
        form = CommentSuggestionsForm()
    return render(request, 'suggestions/customer_suggestions.html', {'form':form})

survey/views.py
from django.shortcuts import render

from .models import OurStrengths

from .forms import FoodForm, CleanForm, SurveyAboutUsForm

def survey_page_view(request):
    return render(request, 'survey/survey.html')


def survey_list_view(request):
    if request.method =='POST':
        food_form = FoodForm(request.POST)
        if food_form.is_valid():
            food_form.save()
            food_form = FoodForm()
    else:
        food_form = FoodForm()
    return render(request, 'survey/survey_list.html', context={'form':food_form})



def survey_abuout_us_view(request):
    strengths = OurStrengths.objects.all()
    if request.method =='POST':
        form = SurveyAboutUsForm(request.POST)
        if form.is_valid():
            form.save()
            form = SurveyAboutUsForm()
    else:
        form = SurveyAboutUsForm()
    return render(request, 'survey/survey_about_us.html', context={'form':form, 'strengths':strengths})




def survey_clean_view(request):
    if request.method =='POST':
        clean_form = CleanForm(request.POST)
        if clean_form.is_valid():
            clean_form.save()
            clean_form = CleanForm()          
    else:
        clean_form = CleanForm()
     
    return render(request, 'survey/survey_clean.html', context={'survey_clean':clean_form})

survey/templates/survey/survey_about_us.html
{% extends "_base.html" %}
{%load crispy_forms_tags %} 
{% load i18n %}

{% load static %}


{% block page_title %}{% trans "survey list" %}{% endblock page_title %}

{% block content %}
    <div class="row columns">
        <div class="large-5 medium-5 float-center">
            <div class="survey_box">
                <div class="page_title">
                    <h2 class="title">{% trans "survey" %}</h2>
                    <a href="{% url "survey:survey" %}" class="back">
                        {% trans "came back" %}
                        <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                            <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                            <g id="SVGRepo_iconCarrier">
                                <path
                                    d="M14.9991 19L9.83911 14C9.56672 13.7429 9.34974 13.433 9.20142 13.0891C9.0531 12.7452 8.97656 12.3745 8.97656 12C8.97656 11.6255 9.0531 11.2548 9.20142 10.9109C9.34974 10.567 9.56672 10.2571 9.83911 10L14.9991 5"
                                    stroke="#b30000" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
                                </path>
                            </g>
                        </svg>
                    </a>
                </div>
                <ul class="survey_list">
                    <li class="item">
                        <div class="title">۲.{% trans " Services and servicing of the collection" %}</div>
                        <div class="rating">
                            <button data-rate="4" data-open="Modal_2">
                                <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                                    <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                                    <g id="SVGRepo_iconCarrier">
                                        <path
                                            d="M8.88875 14.5414C8.63822 14.0559 8.0431 13.8607 7.55301 14.1058C7.05903 14.3528 6.8588 14.9535 7.10579 15.4474C7.18825 15.6118 7.29326 15.7659 7.40334 15.9127C7.58615 16.1565 7.8621 16.4704 8.25052 16.7811C9.04005 17.4127 10.2573 18.0002 12.0002 18.0002C13.7431 18.0002 14.9604 17.4127 15.7499 16.7811C16.1383 16.4704 16.4143 16.1565 16.5971 15.9127C16.7076 15.7654 16.8081 15.6113 16.8941 15.4485C17.1387 14.961 16.9352 14.3497 16.4474 14.1058C15.9573 13.8607 15.3622 14.0559 15.1117 14.5414C15.0979 14.5663 14.9097 14.892 14.5005 15.2194C14.0401 15.5877 13.2573 16.0002 12.0002 16.0002C10.7431 16.0002 9.96038 15.5877 9.49991 15.2194C9.09071 14.892 8.90255 14.5663 8.88875 14.5414Z">
                                        </path>
                                        <path
                                            d="M6.5 7C5 7 5 8.66667 5 8.66667C5 10 7.5 12 8 12C8.5 12 11 10 11 8.66667C11 8.66667 11 7 9.5 7C8 7 8 9 8 9C8 9 8 7 6.5 7Z">
                                        </path>
                                        <path
                                            d="M13 8.66667C13 8.66667 13 7 14.5 7C16 7 16 9 16 9C16 9 16 7 17.5 7C19 7 19 8.66667 19 8.66667C19 10 16.5 12 16 12C15.5 12 13 10 13 8.66667Z">
                                        </path>
                                        <path fill-rule="evenodd" clip-rule="evenodd"
                                            d="M12 23C18.0751 23 23 18.0751 23 12C23 5.92487 18.0751 1 12 1C5.92487 1 1 5.92487 1 12C1 18.0751 5.92487 23 12 23ZM12 20.9932C7.03321 20.9932 3.00683 16.9668 3.00683 12C3.00683 7.03321 7.03321 3.00683 12 3.00683C16.9668 3.00683 20.9932 7.03321 20.9932 12C20.9932 16.9668 16.9668 20.9932 12 20.9932Z">
                                        </path>
                                    </g>
                                </svg>
                                <span class="text">{% trans "perfect" %}</span>
                            </button>
                            <button data-rate="3" data-open="Modal_2">
                                <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                                    <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                                    <g id="SVGRepo_iconCarrier">
                                        <path
                                            d="M8.5 11C9.32843 11 10 10.3284 10 9.5C10 8.67157 9.32843 8 8.5 8C7.67157 8 7 8.67157 7 9.5C7 10.3284 7.67157 11 8.5 11Z">
                                        </path>
                                        <path
                                            d="M17 9.5C17 10.3284 16.3284 11 15.5 11C14.6716 11 14 10.3284 14 9.5C14 8.67157 14.6716 8 15.5 8C16.3284 8 17 8.67157 17 9.5Z">
                                        </path>
                                        <path
                                            d="M8.88875 13.5414C8.63822 13.0559 8.0431 12.8607 7.55301 13.1058C7.05903 13.3528 6.8588 13.9535 7.10579 14.4474C7.18825 14.6118 7.29326 14.7659 7.40334 14.9127C7.58615 15.1565 7.8621 15.4704 8.25052 15.7811C9.04005 16.4127 10.2573 17.0002 12.0002 17.0002C13.7431 17.0002 14.9604 16.4127 15.7499 15.7811C16.1383 15.4704 16.4143 15.1565 16.5971 14.9127C16.7076 14.7654 16.8081 14.6113 16.8941 14.4485C17.1387 13.961 16.9352 13.3497 16.4474 13.1058C15.9573 12.8607 15.3622 13.0559 15.1117 13.5414C15.0979 13.5663 14.9097 13.892 14.5005 14.2194C14.0401 14.5877 13.2573 15.0002 12.0002 15.0002C10.7431 15.0002 9.96038 14.5877 9.49991 14.2194C9.09071 13.892 8.90255 13.5663 8.88875 13.5414Z">
                                        </path>
                                        <path fill-rule="evenodd" clip-rule="evenodd"
                                            d="M12 23C18.0751 23 23 18.0751 23 12C23 5.92487 18.0751 1 12 1C5.92487 1 1 5.92487 1 12C1 18.0751 5.92487 23 12 23ZM12 20.9932C7.03321 20.9932 3.00683 16.9668 3.00683 12C3.00683 7.03321 7.03321 3.00683 12 3.00683C16.9668 3.00683 20.9932 7.03321 20.9932 12C20.9932 16.9668 16.9668 20.9932 12 20.9932Z">
                                        </path>
                                    </g>
                                </svg> <span class="text">{% trans "good" %}</span>
                            </button>
                            <button data-rate="2" data-open="Modal_4">
                                <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                                    <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                                    <g id="SVGRepo_iconCarrier">
                                        <path
                                            d="M8.5 11C9.32843 11 10 10.3284 10 9.5C10 8.67157 9.32843 8 8.5 8C7.67157 8 7 8.67157 7 9.5C7 10.3284 7.67157 11 8.5 11Z">
                                        </path>
                                        <path
                                            d="M17 9.5C17 10.3284 16.3284 11 15.5 11C14.6716 11 14 10.3284 14 9.5C14 8.67157 14.6716 8 15.5 8C16.3284 8 17 8.67157 17 9.5Z">
                                        </path>
                                        <path
                                            d="M8 14C7.44772 14 7 14.4477 7 15C7 15.5523 7.44772 16 8 16H15.9991C16.5514 16 17 15.5523 17 15C17 14.4477 16.5523 14 16 14H8Z">
                                        </path>
                                        <path fill-rule="evenodd" clip-rule="evenodd"
                                            d="M12 23C18.0751 23 23 18.0751 23 12C23 5.92487 18.0751 1 12 1C5.92487 1 1 5.92487 1 12C1 18.0751 5.92487 23 12 23ZM12 20.9932C7.03321 20.9932 3.00683 16.9668 3.00683 12C3.00683 7.03321 7.03321 3.00683 12 3.00683C16.9668 3.00683 20.9932 7.03321 20.9932 12C20.9932 16.9668 16.9668 20.9932 12 20.9932Z">
                                        </path>
                                    </g>
                                </svg> <span class="text">{% trans "suitable" %}</span>
                            </button>
                            <button class="clicked" data-rate="1" data-open="Modal_4">
                                <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                                    <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                                    <g id="SVGRepo_iconCarrier">
                                        <path
                                            d="M8.5 11C9.32843 11 10 10.3284 10 9.5C10 8.67157 9.32843 8 8.5 8C7.67157 8 7 8.67157 7 9.5C7 10.3284 7.67157 11 8.5 11Z">
                                        </path>
                                        <path
                                            d="M17 9.5C17 10.3284 16.3284 11 15.5 11C14.6716 11 14 10.3284 14 9.5C14 8.67157 14.6716 8 15.5 8C16.3284 8 17 8.67157 17 9.5Z">
                                        </path>
                                        <path
                                            d="M15.1091 16.4588C15.3597 16.9443 15.9548 17.1395 16.4449 16.8944C16.9388 16.6474 17.1391 16.0468 16.8921 15.5528C16.8096 15.3884 16.7046 15.2343 16.5945 15.0875C16.4117 14.8438 16.1358 14.5299 15.7473 14.2191C14.9578 13.5875 13.7406 13 11.9977 13C10.2547 13 9.03749 13.5875 8.24796 14.2191C7.85954 14.5299 7.58359 14.8438 7.40078 15.0875C7.29028 15.2348 7.1898 15.3889 7.10376 15.5517C6.85913 16.0392 7.06265 16.6505 7.55044 16.8944C8.04053 17.1395 8.63565 16.9443 8.88619 16.4588C8.9 16.4339 9.08816 16.1082 9.49735 15.7809C9.95782 15.4125 10.7406 15 11.9977 15C13.2547 15 14.0375 15.4125 14.498 15.7809C14.9072 16.1082 15.0953 16.4339 15.1091 16.4588Z">
                                        </path>
                                        <path fill-rule="evenodd" clip-rule="evenodd"
                                            d="M12 23C18.0751 23 23 18.0751 23 12C23 5.92487 18.0751 1 12 1C5.92487 1 1 5.92487 1 12C1 18.0751 5.92487 23 12 23ZM12 20.9932C7.03321 20.9932 3.00683 16.9668 3.00683 12C3.00683 7.03321 7.03321 3.00683 12 3.00683C16.9668 3.00683 20.9932 7.03321 20.9932 12C20.9932 16.9668 16.9668 20.9932 12 20.9932Z">
                                        </path>
                                    </g>
                                </svg> <span class="text">{% trans "weak" %}</span>
                            </button>

                        </div>
                    </li>
                </ul>

                <div class="form_button_container">
                    <a href="{% url "suggestions:suggestions" %}" class="button large expanded green">
                        <span class="text">{% trans "The next step" %}</span>
                    </a>
                </div>

            </div>
        </div>
    </div>
    <!-- Modal_2 -->
    <div class="reveal custom_popup" id="Modal_2" data-reveal>
        <h1 class="modal_title">{% trans " in your opinion" %}</h1>
        <div class="checkbox_group">
            <!-- start item -->
             {% for item in strengths %}
                <label class="control checkbox_element">
                    <span class="text">{{item.title}}</span>
                    
                    <input type="checkbox"  />
                    <div class="element_indicator"></div>
                </label>
             {% endfor %}
            <!-- //end item -->
            <!-- //end item -->
        </div>
            {% comment %} <form >
                {% csrf_token %}
                {{form|crispy}}
            <div class="modal_button_container">
                <button class="button large expanded green" data-close>
                    <span class="text">{% trans "The next step" %}</span>
                </button>
            </div>
            <form> {% endcomment %}

    </div>
    <!-- // end Modal_2 -->
{% endblock content %}

{% block script %}
    <script src="{% static "js/jquery-3.7.1.min.js" %}"></script>
    <script src="{% static "js/foundation.min.js" %}"></script>
    <script src="{% static "js/app.js" %}"></script>
{% endblock script %}

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html dir="rtl">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block page_title %}{% endblock page_title %}</title>
    <link rel="stylesheet" href="{% static "css/foundation-float.css" %}">

    <link rel="stylesheet" href="{% static "css/app.css" %}">

</head>

<body>
    {% block content %}
    {% endblock content %}

    {% block script %}
    {% endblock script %}
</body>

</html>